# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

require 'cucumber/rails'
require 'capybara'
require 'capybara/cucumber'
require 'selenium-webdriver'
require 'pry'
require 'cucumber/rails/world'
require 'cucumber/rspec/doubles'

ENV["RAILS_ENV"] ||= 'test'
require File.expand_path(File.dirname(__FILE__) + '/../../config/environment')

# ********headless browser config below*********
Capybara.register_driver :selenium_chrome do |app|
  options = Selenium::WebDriver::Chrome::Options.new
  options.add_argument('window-size=1240,1400')
  options.add_preference('download.default_directory', DownloadHelpers::PATH.to_s)
  options.add_preference('prompt_for_download', false)
  options.add_preference(:browser, set_download_behavior: { behavior: 'allow' })
  options.headless!

  Capybara::Selenium::Driver.new(app, browser: :chrome, options: options)
end

Capybara.register_driver :selenium_chrome_headless do |app|
  options = Selenium::WebDriver::Chrome::Options.new
  options.add_argument('window-size=1240,1400')
  options.add_argument('headless')
  options.add_argument('disable-gpu')
  options.add_preference('download.default_directory', DownloadHelpers::PATH.to_s)
  options.add_preference('prompt_for_download', false)
  options.add_preference(:browser, set_download_behavior: { behavior: 'allow' })

  driver = Capybara::Selenium::Driver.new(app, browser: :chrome, options: options)

  ### Allow file downloads in Google Chrome when headless!!!
  ### https://bugs.chromium.org/p/chromium/issues/detail?id=696481#c89
  bridge = driver.browser.send(:bridge)

  path = '/session/:session_id/chromium/send_command'
  path[':session_id'] = bridge.session_id

  bridge.http.call(
    :post,
    path,
    cmd: 'Page.setDownloadBehavior',
    params: {
      behavior: 'allow',
      downloadPath: DownloadHelpers::PATH.to_s
    }
  )

  driver
end

Capybara.javascript_driver = ENV['GUI'] ? :selenium_chrome : :selenium_chrome_headless

Capybara.default_max_wait_time = 15

Capybara.default_host = 'http://localhost:3000'

World(FactoryBot::Syntax::Methods)